### ISSUE TITLE
MOSN Logo 社区投票

### ISSUE THREAD

**Issue by nejisama** [mosn/community#2]
MOSN 的 logo 升级，希望社区投票选择，包括现用的 logo 和新创建的两个 logo 在内一共三个方案，请大家投票。选择完成 MOSN 的 logo 将会更新到官网 https://mosn.io 及其他渠道。

**请在 issue 中回复你选择的方案，并给出简要的选择说明。**

### MOSN 介绍

MOSN 是一款使用 Go 语言开发的网络代理软件，作为云原生的网络数据平面，旨在为服务提供多协议，模块化，智能化，安全的代理能力。MOSN 是 Modular Open Smart Network 的简称。MOSN 可以与任何支持 xDS API 的 Service Mesh 集成，亦可以作为独立的四、七层负载均衡，API Gateway，云原生 Ingress 等使用。

#### 投票说明

- 投票方式：回复本条 issue 你喜欢的方案编号；
- 投票时间：即日起到 2020 年 3 月 26 日；
公开结果时间和形式：将在 3月 26 日 MOSN 线上直播技术分享后公布，直播地址：https://tech.antfin.com/community/live/1131

#### 详细 Logo 提案

![image](https://user-images.githubusercontent.com/16449274/76731585-b524d000-6798-11ea-87aa-67cc9ce70292.png)

##### 方案 1（原 Logo）：体现“外挂”、“融合”

![image](https://user-images.githubusercontent.com/16449274/76731625-cf5eae00-6798-11ea-980e-91ed7b869fed.png)

##### 方案 2：体现：“速度快”、“效率高”、“传输”

![image](https://user-images.githubusercontent.com/16449274/76731638-d980ac80-6798-11ea-9d6d-25af8c75e56f.png)

##### 方案 3：强调“传输”和“方向”，选用飞机/箭头这个熟悉的图形来强调

![image](https://user-images.githubusercontent.com/16449274/76731655-e56c6e80-6798-11ea-934f-83d626381f47.png)

#### 回复 issue，投出你的一票吧！

![image](https://user-images.githubusercontent.com/16449274/76731677-f2895d80-6798-11ea-8713-ee1229c6e47a.png)

**Comment by TreeLin** [comment]
方案三

**Comment by rootsongjc** [comment]
我选择**方案三**，更生动、活动、形象，带有指向性。
![image](https://user-images.githubusercontent.com/3328185/76733117-26658280-679b-11ea-837a-872959b7e14c.png)

**Comment by CodingSinger** [comment]
方案一

**Comment by Candicepan** [comment]
方案三

**Comment by wanderxjtu** [comment]
方案二

**Comment by trainyao** [comment]
方案一

**Comment by JasonRD** [comment]
方案一

**Comment by wangpeng3477** [comment]
方案三

**Comment by extracoded** [comment]
方案三

**Comment by taoyuanyuan** [comment]
选方案一， 菱角分明，一看就很有个性
方案二没看懂， 方案三翅膀耷拉着，像运输机
![image](https://user-images.githubusercontent.com/2707372/76749157-03e16280-67b7-11ea-9d03-c2924bd2ebd2.png)

**Comment by wangfakang** [comment]
方案一
0、图标1在社区里面已经曝光比较的多了，一看见这个图标就想到了MOSN。
1、图标1整体视觉上看起来更融洽。

**Comment by ujjboy** [comment]
选方案一。 因为方案二一眼看上不是很完整，分叉很多给人感觉不好。 方案三没有识别度，和飞书、SS、telegram 太像了

**Comment by InfoHunter** [comment]
方案一

2体现不出来字母M，3的话和某著名翻墙工具极其神似……

**Comment by rootsongjc** [comment]
大家选择的时候请同时给出选择该方案的原因（修改自己的comment 即可）。@InfoHunter @ujjboy @wangfakang @taoyuanyuan @extracoded @wangp @JasonRD @trainyao @wangderxjtu

**Comment by Tony-Hangzhou** [comment]
选 1 设计上，整体感强些；3 的设计简洁，美工上要想下。

**Comment by GLYASAI** [comment]
方案 1. 
 2, 3 方案 MOSN 几个字太大了. 方案一字的大小挺合适

**Comment by rootsongjc** [comment]
@GLYASAI logo 是可以根据大家的评论调整的，如果 2、3 的字体调小了，你还会选择方案一吗？

**Comment by rootsongjc** [comment]
有些人反应 MOSN 的 logo 有些像 Shadowsocks，我把它们放到一张图片里，大家可以对比下。

![image](https://user-images.githubusercontent.com/3328185/76744941-ff657b80-67af-11ea-963a-c0049772bb73.png)


还是可以看出有不小的区别的，使用飞机表示通信和传输的 logo 确实也不少。

**Comment by carolove** [comment]
方案 一

**Comment by tanjunchen** [comment]
方案 一 +1

**Comment by lbsha** [comment]
方案一

**Comment by hb-chen** [comment]
方案一，含义符合代理，整体感也好
二的icon中没看出效率、速度和传输，而且icon感觉差个时代
三的icon太没识别度了

**Comment by khotyn** [comment]
三的方案识别度太低了，和 Telegram 的很像，如果不看文字介绍，不知道里面还藏了一个 M，是否在图标上把 M 突出一下？这样也可以提高识别度。

以下是 Telegram 其中的一个 Icon：

![image](https://user-images.githubusercontent.com/584455/76749896-3f306100-67b8-11ea-8093-f66e62f63ae8.png)

**Comment by yansousou** [comment]
方案一：这个整体看起来很简约，一眼望去感觉和某个产品的图标类似
方案二：突出这个产品的特点，比较明了， 而且logo和很好识别
方案三：更加简约 单独看方案三是很漂亮 但是看不出产品功能

相比之下方案二更好点。

**Comment by luxious** [comment]
一好，因为是六边形，一般一眼看上去会联想到蜂巢，而蜂巢里的蜜蜂给人一种忙碌而且协作很高效的感觉。

**Comment by Ghostbaby** [comment]
方案三，本身就是一个完整的产品，可以独立于第三方单独飞翔，同时体现出轻量级的特性。

**Comment by echooymxq** [comment]
我倒觉得可以在方案一的基础上嵌入一个M进去，保持SOFA系列基本以六边形构建图标，也类比Envoy，方案三倒让我感觉有点类似于Istio的味道。

**Comment by yuyicai** [comment]
方案三

**Comment by rootsongjc** [comment]
@echooymxq MOSN 的 logo 设计没必要拘泥于 SOFAStack 的风格，毕竟 MOSN 已经从 SOFAStack 中迁出了。

**Comment by qunqiang** [comment]
方案三

我喜欢天蓝色， 看完上面的留言，发现融合了M ，但是真的不明显

**Comment by rootsongjc** [comment]
这是方案一的效果图，如果使用反白的 logo 放在 [mosn 官网](https://mosn.io)上，其实辨识度还挺高的，起码不会引起歧义。

下面是使用方案一的网站预览图，供大家参考。

### 使用反白方案一 logo，同时使用原 logo 文字

![image](https://user-images.githubusercontent.com/3328185/76814088-cfac8700-6834-11ea-8325-c71ae4ed881d.png)

### 使用反白方案一 logo，不使用原 logo 文字

![image](https://user-images.githubusercontent.com/3328185/76814288-55303700-6835-11ea-98ae-90338417f0ec.png)

不知大家怎么看以上两种预览效果？哪种好一点？

**Comment by f2h2h1** [comment]
方案 1.
方案 1. 辨识度高，
方案 2. 太抽象了，很难联想到那几个内核元素
方案 3. 像 ss 的图标

**Comment by sunny0826** [comment]
方案一+1

**Comment by token01** [comment]
方案一—+1

**Comment by 4quard** [comment]
方案一，还是熟悉的味道

**Comment by cytyikai** [comment]
方案一

**Comment by fanyanming2016** [comment]
方案一 识别度高

**Comment by y573724537** [comment]
方案三

**Comment by inkinworld** [comment]
方案一
辨识度高，与蚂蚁项目格调更统一。

**Comment by dllen** [comment]
方案一

**Comment by meua** [comment]
1

**Comment by wenxuwan** [comment]
1

**Comment by zonghaishang** [comment]
方案一

**Comment by wyzhangjie** [comment]
方案一

**Comment by Candicepan** [comment]
截止 2020年3月26日20:00，有效票数 35 票。方案一 25 票，占比 71.43%；方案二 2 票，占比 5.71%；方案三 8 票，占比 22.86%。最终，方案一大比分胜出，方案一 为 MOSN 最终 Logo 。感谢大家参与社区建设。

**Comment by rootsongjc** [comment]
官网 Logo 已更新，大家可以打开 [mosn.io](https://mosn.io) 查看。
![image](https://user-images.githubusercontent.com/3328185/77646611-d8712b80-6f9f-11ea-8c56-a2a8f27ee467.png)
