### ISSUE TITLE
REQUEST: New membership for peacocktrain

### ISSUE THREAD

**Issue by peacocktrain** [mosn/community#6]
## GitHub user id

peacocktrain

## Company affiliation

Boss直聘

## Requirements
- [x]  I have reviewed the community [roles](https://github.com/mosn/community/blob/master/ROLES.md) guidelines
- [x]  I have enabled 2FA on my GitHub account
- [x]  I have joined the MOSN DingTalk(钉钉) or Slack

Provide a link to at least one PR that you have successfully pushed to one
of the MOSN repositories.

- https://github.com/mosn/mosn/pull/1080
- https://github.com/mosn/pkg/pull/8
- https://github.com/mosn/mosn/pull/1046

**Comment by rootsongjc** [comment]
@cch123 @taoyuanyuan @nejisama @wangfakang  Given his tremendous contributions to the MOSN community, I propose to certify him as a MOSN Committer, what do you guys think?

**Comment by cch123** [comment]
+1

**Comment by wangfakang** [comment]
+1

**Comment by nejisama** [comment]
+1

**Comment by taoyuanyuan** [comment]
+1

**Comment by rootsongjc** [comment]
@peacocktrain You are invited to join the MOSN maintainer team.
