### ISSUE TITLE
REQUEST: New membership for arugal

### ISSUE THREAD

**Issue by rainbend** [mosn/community#7]
## GitHub user id

arugal

## Company affiliation

ActionSky

## Requirements
- [x]  I have reviewed the community [roles](https://github.com/mosn/community/blob/master/ROLES.md) guidelines
- [x]  I have enabled 2FA on my GitHub account
- [x]  I have joined the MOSN DingTalk(钉钉) or Slack

Provide a link to at least one PR that you have successfully pushed to one
of the MOSN repositories.
https://github.com/mosn/mosn/pull/1061

**Comment by rootsongjc** [comment]
Approved. You are invited to join the MOSN GitHub organization. Welcome aboard!
