### ISSUE TITLE
REQUEST: New membership for trainyao

### ISSUE THREAD

**Issue by trainyao** [mosn/community#9]
## GitHub user id
trainyao

## Company affiliation
有米科技(广州)

## Requirements
- [x]  I have reviewed the community [roles](https://github.com/mosn/community/blob/master/ROLES.md) guidelines
- [x]  I have enabled 2FA on my GitHub account
- [x]  I have joined the MOSN DingTalk(钉钉) or Slack

Provide a link to at least one PR that you have successfully pushed to one
of the MOSN repositories.

[#1118](https://github.com/mosn/mosn/pull/1118)
[#1102](https://github.com/mosn/mosn/pull/1102)
[#1089](https://github.com/mosn/mosn/pull/1089)
[#1068](https://github.com/mosn/mosn/pull/1068)

**Comment by rootsongjc** [comment]
Thank you for your contribution to the MOSN community. The MOSN community wants to certify you as a committer. @mosn/committer

**Comment by wangfakang** [comment]
@trainyao  has made many contributions in MOSN with Istio WG, welcome trainyao.
